name: Advent of Code Runner Setup

on:
  workflow_call:
    inputs:
      release:
        required: false
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      runner-path: ${{ steps.set-runner-path.outputs.runner-path }}
    steps:
      # Checkout the repository with submodules
      - name: Checkout Advent-of-Code-Runner
        uses: actions/checkout@v4
        with:
          repository: brandonhippe/Advent-of-Code-Runner
          submodules: recursive
          path: runner
          ref: ${{ inputs.release }}

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # Install dependencies for the runner submodule & submodules
      - name: Setup Runner
        id: set-runner-path
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr libtesseract-dev
          cd runner && python -m pip install -e . && cd ${{ github.workspace }}
          echo "::set-output name=runner-path::${{ github.workspace }}/runner"
