name: Advent of Code Runner Setup

on:
  workflow_call:
    inputs:
      release:
        required: false
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
    steps:
      # Checkout the repository with submodules
      - uses: actions/checkout@v4
        with:
          repository: brandonhippe/Advent-of-Code-Runner
          submodules: recursive
          path: runner
          ref: ${{ inputs.release }}

      # Set up Python environment
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      # Install dependencies for the runner submodule & submodules
      - name: setup
        run: |
          sudo apt-get update
          sudo apt install tesseract-ocr libtesseract-dev
          cd runner && python -m pip install -e . && cd ${{ github.workspace }}

      # Create docker image
      - name: Docker Image
        run: |
          docker build -t aoc_runner:$GITHUB_SHA
          mkdir -p artifacts
          docker save aoc_runner:$GITHUB_SHA > artifacts/docker-image.tar

      # Temporarily save docker image
      - uses: actions/upload-artifact@v4
        with:
          name: docker-artifact
          path: artifacts
          retention-days: 1
    
